trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    test -f README.md || (echo "No hay README.md en la raíz" && exit 1)
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp README.md $(Build.ArtifactStagingDirectory)/
  displayName: "Copiar README.md"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
