trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 7'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

# Restaura, compila y publica (cambia la ruta del .csproj si es necesario)
- script: |
    dotnet restore
    dotnet publish ./YourWebApp/YourWebApp.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Build & Publish'

# Empaqueta en zip
- task: ArchiveFiles@2
  displayName: 'Zip publish folder'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# Publica artefacto
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    artifactName: 'drop'
